### PR TITLE
added splash screen

### PR DESCRIPTION
**Pull request by fosterer**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
I have added a splash screen to the website.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@fosterer can you please answer all the questions mentioned in the PR template along with that attach screenshots of how your changes are looking on the website, It would make it easier for me to review your PR.

**Comment by fosterer** [comment]
Related Issue
Info about Issue or bug
Closes: #[issue number that will be closed through this PR]

Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

Describe the changes you've made
I have added a splash screen to the website.

Describe if there is any unusual behaviour of your code(Write NA if there isn't)
NA

Checklist:

- [done ]  My code follows the style guidelines of this project.

 

- [done ] I have performed a self-review of my own code.

 

- [done ] I have commented my code, particularly in hard-to-understand areas.

Screenshot of the project here.
Screenshot (522)

**Comment by fosterer** [comment]
> @fosterer can you please answer all the questions mentioned in the PR template along with that attach screenshots of how your changes are looking on the website, It would make it easier for me to review your PR.

I have answered all questions . Please have a look .

**Comment by yashikabhargava** [comment]
@fosterer Thank you for taking out your valuable time to contribute to the project but I do not feel the need of adding a splash screen to the website as it already has a landing page. Hence, I'll be closing this PR without merging it.

But you are more than welcome to contribute to this project by raising some other issue, Please do raise an issue first as it helps to discuss the changes that you are planning on doing.
Thanks : )

**Pull request closed without merging**
