### PR TITLE
#73 refactoring codebase

### PR DESCRIPTION
**Pull request by ShubhamPatil0723**
## Related Issue
  - Refactoring codebase

Closes: #73

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.

### Describe the changes you've made
- Divided the code of HTML into different pages
- Moved resources section from landing page to resources page for better UI

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

### Landing Page 
Landing page

### Resources Page
Resources page

### Content Page
Content page

### CODE REVIEW

**Comment by ShubhamPatil0723** [comment]
The CSS file contains a lot of redundant code which could be reduced but we will have to write it again. Along with this some files contains Bootstrap code and some contain CSS so we need to decide whether we should stick to vanilla CSS or Bootstrap because it is making hard to debug elements behaviour @yashikabhargava

**Comment by yashikabhargava** [comment]
@ShubhamPatil0723 Thank you for refactoring the HTML file.

And yes CSS file contains a lot of redundant code, I think we should reduce the code by re-writing it.
About whether to stick with bootstrap or vanilla CSS, Maybe we should stick with vanilla CSS as a lot of code is in that only, what is your advice?

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
@ShubhamPatil0723 I'm merging this PR, for the CSS file please open another PR.

**Comment by yashikabhargava** [comment]
@ShubhamPatil0723 kindly do not start working on the CSS file yet I making some changes as the project was not loading on github pages, start working afterwards.

**Comment by ShubhamPatil0723** [comment]
> @ShubhamPatil0723 Thank you for refactoring the HTML file.
> 
> And yes CSS file contains a lot of redundant code, I think we should reduce the code by re-writing it. About whether to stick with bootstrap or vanilla CSS, Maybe we should stick with vanilla CSS as a lot of code is in that only, what is your advice?

Yeah, it would be better if we stick with CSS only.  But I won't be able to work on it right now since I have to do some college work 😅

**Comment by yashikabhargava** [comment]
> > @ShubhamPatil0723 Thank you for refactoring the HTML file.
> > And yes CSS file contains a lot of redundant code, I think we should reduce the code by re-writing it. About whether to stick with bootstrap or vanilla CSS, Maybe we should stick with vanilla CSS as a lot of code is in that only, what is your advice?
> 
> Yeah, it would be better if we stick with CSS only. But I won't be able to work on it right now since I have to do some college work 😅

It's Okay,No problem! Thank you for contributing.

**Pull request merged**
