### PR TITLE
Navigation for resources is created

### PR DESCRIPTION
**Pull request by Laxmankohar**
## Related Issue
  - Info about Issue or bug

Closes: #19 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
I have made changes in navbar of  index.html and  add some css to style the navigation of resources in style.css.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots

Screenshot (135)
Screenshot (136)

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@Laxmankohar Please resolve the merge conflicts, then only I'll be able to merge this PR.

**Comment by yashikabhargava** [comment]
@Laxmankohar The code for resources has been divided into different pages hence please add link to those pages instead of the id.
Thanks

**Comment by Laxmankohar** [comment]
ok

**Comment by Laxmankohar** [comment]
@yashikabhargava Should i have to make new pull request?

**Comment by Laxmankohar** [comment]
> @Laxmankohar The code for resources has been divided into different pages hence please add link to those pages instead of the id. Thanks

I have added the link to every pages of resources. Should i have to make a new pull request?
Screenshot (138)

**Comment by yashikabhargava** [comment]
> > @Laxmankohar The code for resources has been divided into different pages hence please add link to those pages instead of the id. Thanks
> 
> I have added the link to every pages of resources. Should i have to make a new pull request? Screenshot (138)

Yes, kindly open a new pull request.

**Pull request closed without merging**
