### PR TITLE
contact box change

### PR DESCRIPTION
**Pull request by Prashant7451**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
Changed the contact box and redesigned it using bootstrap which makes it more suitable.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### Screenshots

ss

### CODE REVIEW

**Comment by yashikabhargava** [comment]
Looks good but the color of the button does not seem to be matching with the rest of the website. Also, the color of "Drop up a message" is a bit dark. Can you fix this and share the update again?
Thanks

**Comment by Prashant7451** [comment]
Ya sure ,,,welcome.would update you in a while

**Comment by Prashant7451** [comment]
ss2
made it in combination with upper homepage,,,drop up a message was dark because it has a white background.But how is it now?

**Comment by yashikabhargava** [comment]
> Should i raise a pr?

You have already raised this PR, just edit this one and answer all the questions. Also, Please link the issue this PR is closing.

**Pull request closed without merging**
