### PR TITLE
FEAT: icons resources added

### PR DESCRIPTION
**Pull request by Heismanish**
Some handy icons resources has been added to the site and is working well.

### CODE REVIEW

**Comment by yashikabhargava** [comment]
Sounds great, can you please provide screenshots of how your changes are looking on the website?
Thanks

**Comment by Heismanish** [comment]
Yes here it is, there is heroicons and ionicons in the icons section of the page. 
Screenshot from 2022-10-02 11-56-27

**Comment by yashikabhargava** [comment]
Thank you for contributing: )

**Review by yashikabhargava — COMMENTED** [review]
Approved

**Pull request merged**
