### PR TITLE
Designed scrollbar and added padding

### PR DESCRIPTION
**Pull request by Abhijeet03s**
## Related Issue
 Designed Scrollbar and Added padding between headings

Closes: #45

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.

### Describe the changes you've made
  - Design scrollbar
  - Added padding and margin to make UI clean (check screenshots)

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Screenshots
changes-scrollbar-design

added-margin-on-inner-heading

### CODE REVIEW

**Comment by Abhijeet03s** [comment]
Please review the issue section, Yashika. I generated the issue. Please merge the PR if you like the modifications. And do let me know if you believe I need to make any other changes.

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
> Please review the issue section, Yashika. I generated the issue. Please merge the PR if you like the modifications. And do let me know if you believe I need to make any other changes.

Thank you for raising the issue, the changes look great.

**Comment by yashikabhargava** [comment]
Thank you for contributing : )

**Comment by Abhijeet03s** [comment]
Glad you like the work. Happy to contribute to your project.

**Pull request merged**
