### PR TITLE
Added dark theme toggle button

### PR DESCRIPTION
**Pull request by Laxmankohar**
## Related Issue
  - Info about Issue or bug

Closes: #47 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
Added toggle button to the website.
Added html code for toggle button in index.html and added CSS code in style.css.
Created main.js file to include javascript code  and script tag is added into index.html.

### Checklist:
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Adityasaini10012001** [comment]
can you assign this to me.

**Comment by yashikabhargava** [comment]
@Laxmankohar Can you please share screenshots of how your changes are looking on the website?
Thanks

**Comment by Laxmankohar** [comment]
Screenshot (129)
Screenshot (130)
Screenshot (131)
Screenshot (132)

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
@Laxmankohar Great work, Thank you for contributing.

**Pull request merged**
