### PR TITLE
make website responsive in tablets

### PR DESCRIPTION
**Pull request by MD-ARBAB-SAHID**
## Related Issue
  - Webiste not responsive at certain breakpoints

Closes: #62 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.

### Describe the changes you've made
Added bootstrap cards and breakpoints.

### Screenshots
Screenshot 2022-10-05 at 7 12 06 PM

Screenshot 2022-10-05 at 7 12 25 PM

Screenshot 2022-10-05 at 7 12 38 PM

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID please attach the screenshots of how your changes are looking on the website.
Thanks

**Comment by MD-ARBAB-SAHID** [comment]
Added Screenshots @yashikabhargava

**Comment by MD-ARBAB-SAHID** [comment]
Also added links to the websites which were missing and alt tags for images.

**Comment by yashikabhargava** [comment]
> Also added links to the websites which were missing and alt tags for images.

Great, just one thing the size of the cards is uneven which does not look good. will you be able to fix that? Also kindly resolve merge conflicts.
Thanks

**Comment by MD-ARBAB-SAHID** [comment]
Sure.
Do you want the bottom white spaces to be blank or shall I increase the image height and make the object fit: cover retaining its aspect ratio inorder to fully utilise the height ?
Screenshot 2022-10-05 at 8 16 31 PM
Screenshot 2022-10-05 at 8 16 02 PM

**Comment by yashikabhargava** [comment]
> Sure. Do you want the bottom white spaces to be blank or shall I increase the image height and make the object fit: cover retaining its aspect ratio inorder to fully utilise the height ? Screenshot 2022-10-05 at 8 16 31 PM Screenshot 2022-10-05 at 8 16 02 PM

let it be white.

**Comment by MD-ARBAB-SAHID** [comment]
Done . Resolved merge conflicts too. @yashikabhargava

**Review by yashikabhargava — APPROVED** [review]

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
Great work! Thank you for contributing, looking forward to more such contributions.

**Pull request merged**
