### PR TITLE
Share button added |  mobile responsive as well

### PR DESCRIPTION
**Pull request by grraghav120**
## Related Issue
  -Share button added |  mobile responsive as well

Closes: #26 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
- Made changes in index.html

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA everything is working proper from my end.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
image

### CODE REVIEW

**Comment by grraghav120** [comment]
Kindly check I had added share icons.

**Comment by yashikabhargava** [comment]
I'm sorry, forgot to mention, but please add icons for only Twitter, LinkedIn, GitHub, and if possible then also for hashnode.

**Comment by grraghav120** [comment]
Okay got it

**Comment by grraghav120** [comment]
These are the Share buttons @yashikabhargava on github we can;t share as you said to add github button .. But ya along with share button i can add follow us button in which we can add github profile to follow.

**Comment by grraghav120** [comment]
Or we can add anyone either **share our page** buttons or **follow us** on Github,Linkedin,Twitter etc.
both functionality are different

**Comment by grraghav120** [comment]
See here are both share buttons at side and follow us on different media as well.
How is it?
image

**Comment by yashikabhargava** [comment]
@grraghav120  Yes, This is looking great. please resolve the conflicts so that I can merge this PR.
Thanks

**Comment by grraghav120** [comment]
Done @yashikabhargava

**Comment by grraghav120** [comment]
Don't forget label Hacktoberfest-accepted

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
Thank you for contributing.

**Pull request merged**
