### PR TITLE
FEAT: New tools added

### PR DESCRIPTION
**Pull request by Ashish-khanagwal**
resolves issue #12 

Added new tools: `Fonts and Typography Tools` and  `Great Colors Tools`

If it requires some changes, ping me.

### CODE REVIEW

**Comment by yashikabhargava** [comment]
This sounds great but can you attach screenshots of how your changes are being reflected on the website?
Thanks

**Comment by Ashish-khanagwal** [comment]
Here you go, I have added these sections at bottom of at present section with proper Attributes

changes

**Comment by yashikabhargava** [comment]
Great work, Thank you for contributing : )

**Review by yashikabhargava — COMMENTED** [review]
Approved

**Pull request merged**
