### PR TITLE
Animation Effect on hover web-x

### PR DESCRIPTION
**Pull request by sakshamvedi**
## Related Issue
  - Animation Effect on hover web-x

Closes: #43 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
I create a animation in style.css so when you hover the web-x than you see the web-x logo moving in 360deg and in bakground planet and stars are moving 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
If any unusual behaviour simple follow these steps      **.nav-area .left-nav a:hover**  -->  delete  -->   animation-name: example;
 
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@sakshamvedi can you please share a screen recording instead of a screenshot seems like your changes are breaking the background image of the landing page. 
Thanks

**Comment by sakshamvedi** [comment]
@yashikabhargava   

https://user-images.githubusercontent.com/65363371/193749368-39fdfb42-17cf-4b46-848c-7e9730b35879.mp4

**Comment by yashikabhargava** [comment]
Please remove the background in the animation it doesn't look good, also it is the reason the landing page image is breaking.
And kindly apply animation to the logo's text only without background. If possible please improve the animation.

**Comment by sakshamvedi** [comment]
https://user-images.githubusercontent.com/65363371/193754086-eb79f6fd-4016-45ad-8903-8be6646f10db.mp4


https://user-images.githubusercontent.com/65363371/193754246-9724ac4a-68f2-45e2-a764-b45b3ce3f716.mp4

**Comment by yashikabhargava** [comment]
Yes, animation looks fine but the background image is still broken, please fix that.
Thanks

**Comment by sakshamvedi** [comment]
https://user-images.githubusercontent.com/65363371/193763149-eea2055e-f2c3-429d-84e0-3ee9a59fee0d.mp4

**Comment by sakshamvedi** [comment]
** background image is still broken**  sorry but I can't understand it properly

**Comment by yashikabhargava** [comment]
As you can see in the screenshot currently the website's landing page has a background image but the changes that have done are somehow breaking that image means it's not visible. So please look into that and fix it.
Thanks

**Comment by sakshamvedi** [comment]
@yashikabhargava  I did it as you said , Thanks

**Comment by sakshamvedi** [comment]
image
image
image

**Comment by yashikabhargava** [comment]
> image
> 
> image
> 
> image

In the second and third sceenshot why is there blue spot.

**Comment by sakshamvedi** [comment]
Actually @yashikabhargava  I gave some animation on hover in navigation menu , when you hover you see a blue cloud type box come behind the navigation menu

**Comment by yashikabhargava** [comment]
Thanks for doing that but I don't feel the need for it please undo it.

**Comment by sakshamvedi** [comment]
@yashikabhargava I did as you said can you please merge it thanks

**Pull request merged**
