### PR TITLE
Update the right navbar button

### PR DESCRIPTION
**Pull request by suvasreeMondalDev**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by yashikabhargava** [comment]
Please provide screenshot of before and after of your performed changes.

**Comment by suvasreeMondalDev** [comment]
### Before changes, background color on hovering on navbar button has more padding, so I reduced that

Screenshot (373)

### After changing, 

Screenshot (362)

**Comment by yashikabhargava** [comment]
I think you have reduced the padding on the left and right a little too much, can please increase it a little bit and also the margin?

**Comment by suvasreeMondalDev** [comment]
### I changed that can you look into that

Screenshot (374)

**Review by yashikabhargava — APPROVED** [review]

**Comment by yashikabhargava** [comment]
Thank you for Contributing.

**Pull request merged**
