### PR TITLE
navbar mobile responsive

### PR DESCRIPTION
**Pull request by piyush362**
## Related Issue
  - Info about Issue or bug
  - navbar is not responsive for mobile

Closes: #29 
Make navbar look good in mobile devices 

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
- make navbar mobile responstive

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.

image

make navbar center for mobile devices and also match the color og hover button with you all over website

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@piyush362 Please link the issue that will be closed via this PR, also complete the checklist and all the questions that were asked in PR.
Thanks

**Comment by piyush362** [comment]
updated

**Comment by piyush362** [comment]
please add hacktoberfest label

**Comment by yashikabhargava** [comment]
Thank you for contributing.

**Pull request merged**
