### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by grraghav120**
Small bit change regarding follow btn.

## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Are you creating this PR under Hacktoberfest
Yes, I'm opening this PR under hacktoberfest.(Please remove this section if you are not a hacktoberfest participant)

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by grraghav120** [comment]
check it just edit some styling of follows

**Comment by yashikabhargava** [comment]
Kindly provide screenshot.

**Comment by grraghav120** [comment]
I don't why this happen at your hosted web page
image

**Comment by grraghav120** [comment]
see from ur side

**Comment by grraghav120** [comment]
Now i had made some changes merge them kindly

**Review by yashikabhargava — APPROVED** [review]

**Pull request merged**
